model_name: "llava-v1.5-7b"
num_layers: 32
layer_module_tmp: "language_model.model.layers.{}"
mlp_module_tmp: "language_model.model.layers.{}.mlp"
attn_module_tmp: "language_model.model.layers.{}.self_attn"
norm_path: "language_model.model.norm"
voc_path: "language_model.lm_head"
